// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukmkxsflqcreenxpdhke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbWt4c2ZscWNyZWVueHBkaGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzU5NjUsImV4cCI6MjA2MDQ1MTk2NX0.b019DgfZPOvLMdbzG-0EIo0t59fYVegJV_5HCSxHtOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);